on:
  pull_request:

concurrency:
  group: rtdworkflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@30a72423c2d652deac129aa0f937966c0518026c
    secrets: inherit
    with:
      python-version: '3.12'
      enable-sphinx-python-dependency-build-checks: false
