on:
  pull_request:

concurrency:
  group: rtdworkflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rtd-docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_rtd.yaml@72ba44455ad0ba7ec1c51027d5360357d1925733
    secrets: inherit
    with:
      python-version: '3.12'
      enable-sphinx-python-dependency-build-checks: false
