name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    strategy:
      matrix:
        param:
          - juju-version: 3.3/stable
            modules: '["test_charm.py", "test_cos.py", "test_database.py", "test_db_migration.py", "test_django.py", "test_django_integrations.py", "test_fastapi.py", "test_go.py", "test_integrations.py", "test_proxy.py", "test_workers.py"]'
          - juju-version: 3.4/stable
            modules: '["test_charm.py", "test_cos.py", "test_database.py", "test_db_migration.py", "test_django.py", "test_django_integrations.py", "test_fastapi.py", "test_go.py", "test_integrations.py", "test_proxy.py", "test_workers.py", "test_workload_tracing.py"]'
          - juju-version: 3.5/stable
            modules: '["test_charm.py", "test_cos.py", "test_database.py", "test_db_migration.py", "test_django.py", "test_django_integrations.py", "test_fastapi.py", "test_go.py", "test_integrations.py", "test_proxy.py", "test_workers.py", "test_workload_tracing.py"]'
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      extra-arguments: -x --localstack-address 172.17.0.1
      pre-run-script: localstack-installation.sh
      charmcraft-channel: latest/edge
      modules: ${{ matrix.param.modules }}
      rockcraft-channel: latest/edge
      juju-channel: ${{ matrix.juju-version }}
      channel: 1.29-strict/stable
      test-timeout: 30
