name: Integration tests

on:
  pull_request:
  schedule:
    - cron: "0 15 * * SAT"

jobs:
  integration-test:
    permissions:
      contents: read
      packages: write
      actions: read
    uses: ./.github/workflows/integration-test.yml
