name: e2e smoke tests with spread

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  run-spread-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: 'stable'

      - name: Install spread
        run: |
          go install github.com/snapcore/spread/cmd/spread@latest

      - name: Run tests
        run: |
          spread github-ci:

      - name: Tmate debugging session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15

