name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
